# Generated by Django 4.0.3 on 2022-03-20 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotes',
            name='amount_due',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='quotes',
            name='suggested_price',
            field=models.IntegerField(null=True),
        ),
    ]
