# Generated by Django 4.0.3 on 2022-03-20 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quotes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gallons_requested', models.IntegerField()),
                ('delivery_address', models.CharField(max_length=30)),
                ('delivery_date', models.DateField()),
                ('suggested_price', models.IntegerField()),
                ('amount_due', models.IntegerField()),
            ],
        ),
    ]
