# Generated by Django 4.0.3 on 2022-03-13 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Snippet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gallons', models.CharField(max_length=4)),
                ('address', models.CharField(max_length=100)),
            ],
        ),
    ]
